# Generated by Django 3.2.6 on 2021-08-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_pregunta_nivel'),
        ('trivias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='preguntas',
            field=models.ManyToManyField(related_name='trivia_preguntas', to='preguntas.Pregunta'),
        ),
    ]
