# Generated by Django 3.2.6 on 2021-08-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0002_trivia_preguntas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='preguntas',
            new_name='pregunta',
        ),
    ]
