# Generated by Django 3.2.6 on 2021-09-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0004_auto_20210828_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='trivia',
        ),
        migrations.AddField(
            model_name='juego',
            name='puntaje',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
