# Generated by Django 3.2.6 on 2021-09-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0005_auto_20210905_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='puntaje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
