# Generated by Django 3.2.6 on 2021-09-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0006_alter_juego_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Facil'), (2, 'Normal'), (3, 'Dificil')], default=2, verbose_name='dificultad'),
        ),
    ]
