# Generated by Django 3.2.6 on 2021-09-06 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0007_juego_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='puntaje',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
