# Generated by Django 3.2.6 on 2021-09-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0008_alter_juego_puntaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trivia',
        ),
    ]
