# Generated by Django 3.2.6 on 2021-08-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Ciencia y Educación'), (2, 'Cultura y arte'), (3, 'Deporte'), (4, 'Economía'), (5, 'Entretenimiento'), (6, 'Historia'), (7, 'Geografía')], default=6, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='preguntas.pregunta')),
            ],
        ),
    ]
