# Generated by Django 3.2.6 on 2021-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Facil'), (2, 'Normal'), (3, 'Dificil')], default=2, verbose_name='dificultad'),
        ),
    ]
