# Generated by Django 3.2.6 on 2021-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(default='pregunta', max_length=120),
            preserve_default=False,
        ),
    ]
