# Generated by Django 3.2.6 on 2021-08-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_pregunta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ciencia y Educación'), (2, 'Cultura y arte'), (3, 'Deporte'), (4, 'Economía'), (5, 'Entretenimiento'), (6, 'Historia'), (7, 'Geografía')], default=6, verbose_name='categoria'),
        ),
    ]
