# Generated by Django 3.2.6 on 2021-08-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_pregunta_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['nivel']},
        ),
    ]
