# Generated by Django 3.2.6 on 2021-08-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_alter_pregunta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=200),
        ),
    ]
